
// Generated by Cadence Genus(TM) Synthesis Solution 22.12-s082_1
// Generated on: May  6 2025 15:57:40 +07 (May  6 2025 08:57:40 UTC)

// Verification Directory fv/counter 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK (ck_out));
endmodule

module counter(clk, rst_n, en, q);
  input clk, rst_n, en;
  output [7:0] q;
  wire clk, rst_n, en;
  wire [7:0] q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, rc_gclk;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (en), .ck_in (clk), .ck_out (rc_gclk), .test (1'b0));
  DFFRHQX1 q_reg_6(.RN (rst_n), .CK (rc_gclk), .D (n_19), .Q (q[6]));
  OAI21XL g291__2398(.A0 (q[6]), .A1 (n_16), .B0 (n_18), .Y (n_19));
  NAND2XL g292__5107(.A (q[6]), .B (n_16), .Y (n_18));
  DFFRHQX1 q_reg_5(.RN (rst_n), .CK (rc_gclk), .D (n_17), .Q (q[5]));
  OA21X1 g294__6260(.A0 (q[5]), .A1 (n_8), .B0 (n_16), .Y (n_17));
  DFFRHQX1 q_reg_3(.RN (rst_n), .CK (rc_gclk), .D (n_15), .Q (q[3]));
  OAI21XL g296__4319(.A0 (q[3]), .A1 (n_7), .B0 (n_13), .Y (n_15));
  NAND2XL g297__8428(.A (q[5]), .B (n_8), .Y (n_16));
  DFFRHQX1 q_reg_7(.RN (rst_n), .CK (rc_gclk), .D (n_14), .Q (q[7]));
  OAI21XL g300__5526(.A0 (q[7]), .A1 (n_9), .B0 (n_11), .Y (n_14));
  NAND2XL g301__6783(.A (q[3]), .B (n_7), .Y (n_13));
  DFFRHQX1 q_reg_2(.RN (rst_n), .CK (rc_gclk), .D (n_10), .Q (q[2]));
  AOI21XL g303__3680(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_12));
  NAND2XL g304__1617(.A (q[7]), .B (n_9), .Y (n_11));
  OA21X1 g305__2802(.A0 (q[2]), .A1 (n_2), .B0 (n_7), .Y (n_10));
  NAND4XL g306__1705(.A (q[5]), .B (q[4]), .C (q[6]), .D (n_6), .Y (n_9));
  NOR2XL g307__5122(.A (n_0), .B (n_5), .Y (n_8));
  NAND2XL g308__8246(.A (q[2]), .B (n_2), .Y (n_7));
  INVXL g309(.A (n_5), .Y (n_6));
  NAND3XL g310__7098(.A (q[2]), .B (q[3]), .C (n_2), .Y (n_5));
  DFFRHQX1 q_reg_1(.RN (rst_n), .CK (rc_gclk), .D (n_4), .Q (q[1]));
  NOR2XL g312__6131(.A (n_3), .B (n_2), .Y (n_4));
  NOR2XL g313__1881(.A (q[0]), .B (q[1]), .Y (n_3));
  AND2XL g314__5115(.A (q[0]), .B (q[1]), .Y (n_2));
  DFFRX1 q_reg_0(.RN (rst_n), .CK (rc_gclk), .D (n_1), .Q (q[0]), .QN (n_1));
  DFFRX1 q_reg_4(.RN (rst_n), .CK (rc_gclk), .D (n_12), .Q (q[4]), .QN (n_0));
endmodule

