
// Generated by Cadence Genus(TM) Synthesis Solution 22.12-s082_1
// Generated on: May  6 2025 15:57:18 +07 (May  6 2025 08:57:18 UTC)

// Verification Directory fv/counter 

`define ONE_HOT_MUX

module add_unsigned(A, B, Z);
  input [7:0] A;
  input B;
  output [7:0] Z;
  wire [7:0] A;
  wire B;
  wire [7:0] Z;
  wire n_19, n_30, n_33, n_35, n_39, n_41, n_45, n_51;
  wire n_52, n_54, n_55, n_57, n_61, n_68, n_70, n_71;
  wire n_72, n_73, n_75, n_80, n_83, n_87, n_89, n_92;
  wire n_93;
  xor g1 (Z[0], A[0], B);
  nand g2 (n_19, A[0], B);
  nand g21 (n_33, n_30, A[1]);
  nor g26 (n_55, n_39, n_35);
  nor g30 (n_61, n_45, n_41);
  nand g36 (n_54, n_52, A[2]);
  nand g38 (n_57, n_55, n_52);
  nand g44 (n_72, n_61, A[6]);
  nand g51 (n_70, n_68, A[4]);
  nand g53 (n_71, n_61, n_68);
  not g55 (n_73, n_72);
  nand g56 (n_75, n_68, n_73);
  xnor g62 (Z[1], n_30, n_80);
  xnor g64 (Z[2], n_52, n_39);
  xnor g67 (Z[3], n_83, n_35);
  xnor g69 (Z[4], n_68, n_45);
  xnor g72 (Z[5], n_87, n_41);
  xnor g74 (Z[6], n_89, n_51);
  xnor g77 (Z[7], n_92, n_93);
  not g80 (n_39, A[2]);
  not g81 (n_35, A[3]);
  not g82 (n_45, A[4]);
  not g83 (n_41, A[5]);
  not g84 (n_51, A[6]);
  not g86 (n_30, n_19);
  not g87 (n_80, A[1]);
  not g88 (n_93, A[7]);
  not g89 (n_52, n_33);
  not g90 (n_83, n_54);
  not g91 (n_68, n_57);
  not g92 (n_87, n_70);
  not g93 (n_89, n_71);
  not g94 (n_92, n_75);
endmodule

module counter(clk, rst_n, en, q);
  input clk, rst_n, en;
  output [7:0] q;
  wire clk, rst_n, en;
  wire [7:0] q;
  wire n_10, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19;
  add_unsigned add_14_16(.A (q), .B (1'b1), .Z ({n_19, n_18, n_17, n_16, n_15, n_14, n_13, n_12}));
  not g1 (n_10, rst_n);
  CDN_flop q_reg_0(.clk (clk), .d (n_12), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[0]));
  CDN_flop q_reg_1(.clk (clk), .d (n_13), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[1]));
  CDN_flop q_reg_2(.clk (clk), .d (n_14), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[2]));
  CDN_flop q_reg_3(.clk (clk), .d (n_15), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[3]));
  CDN_flop q_reg_4(.clk (clk), .d (n_16), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[4]));
  CDN_flop q_reg_5(.clk (clk), .d (n_17), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[5]));
  CDN_flop q_reg_6(.clk (clk), .d (n_18), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[6]));
  CDN_flop q_reg_7(.clk (clk), .d (n_19), .sena (en), .aclr (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (q[7]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
// conformal library_module
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
